config/routes.rb
Rails.application.routes.draw do
  
  root 'users#new'

  get 'sessions/index'

  get 'login' => 'sessions#new', as: 'login_page'

  post 'login' => 'sessions#create', as: 'login'

  get 'sessions/show'

  get 'sessions/edit'

  get 'sessions/update'

  get 'logout' => 'sessions#destroy', as: 'logout'

  get 'users/index' => 'users#index' 

  get 'register' => 'users#new', as: 'register_page'

  post 'register' => 'users#create', as: 'register'

  get 'showuser' => 'users#show', as: 'user'

  get 'users/edit' => 'users#edit', as: 'edit_user'

  patch 'users/update' => 'users#update', as: 'update_user'

  get 'users/delete'


  #LIKES STUFF

  get 'likes/index'

  get 'likes/new'

  get 'likes/create' => 'likes#create', as: 'save_recipe'

  post 'likes/create' => 'likes#create', as: 'add_recipe'

  get 'likes/show' => 'likes#show', as: 'saved_recipes'

  get 'likes/edit'

  get 'likes/update'

  delete 'likes/delete' => 'likes#delete', as: 'unsave_recipe'

# RECIPES

  get 'recipes/index' => 'recipes#index', as: "index"

  get 'recipes/new' => 'recipes#new', as: "find_recipes"

  post 'recipes/new' => 'recipes#new', as: "search_recipes"

  get 'recipes/create' 

  post 'recipes/show' => 'recipes#show', as: 'show_recipe'

  get 'recipes/edit'

  get 'recipes/update'

  delete 'recipes/delete'

#MEALS 

  get 'meals/index'

  get 'meals/new'

  post 'meals/create' => 'meals#create', as: 'add_meal'

  post 'meals/show' => 'meals#show', as: 'show_meal'

  get 'meals/edit'

  get 'meals/update'

  delete 'meals/delete' => 'meals#delete', as: 'delete_meal'

 #MEALPLAN
 
  get 'mealplan/index' => 'mealplan#index', as: 'mealplans'

  get 'mealplan/new' => 'mealplan#new', as: 'start_mealplan'

  post 'mealplan/new' => 'mealplan#new', as: 'new_mealplan'

  post 'mealplan/create' => 'mealplan#create', as: 'create_mealplan'

  get 'mealplan/show' 

  get 'mealplan/edit'

  get 'mealplan/update'

  delete 'mealplan/delete' 

#ITEMS

  get 'items/index'

  get 'items/new'

  get 'items/create' => 'items#create', as: 'create_items'

  get 'items/show' 

  get 'items/edit'

  get 'items/update'

  delete 'items/delete'

  #INGREDIENTS

  get 'ingredients/index'

  get 'ingredients/new'

  get 'ingredients/create' => 'ingredients#create', as: "add_ingredient"

  get 'ingredients/show' 

  get 'ingredients/edit'

  get 'ingredients/update'

  delete 'ingredients/delete'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :item
  belongs_to :meal
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :ingredients, dependent: :destory
	has_many :meals, through: :ingredients
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :mealplan
  belongs_to :user
  has_many :ingredients, dependent: :destroy
  has_many :items, through: :ingredients
end

app/models/mealplan.rb
class Mealplan < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :likes
  has_many :meals
  has_many :mealplans
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

  def new
  end

  def create
    recipe = session[:recipe]
    ingredients = recipe['recipe']['ingredients']
    p ingredients
    list = []
    ingredients.each do |ing|
      item = Item.new
      item.name = ing
      item.save
      list.push(item.id)
    end  
    session[:list] = list
    return redirect_to add_ingredient_path
  end

  def show
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
  end

  def new
  end

  def create
    like = Like.new
    like.title = params[:title]
    like.recipe_id = params[:id]
    like.publisher = params[:publisher]
    like.publisher_url = params[:publisher_url]
    like.rank = params[:rank]
    like.img = params[:img]
    like.user = current_user
    like.save
    return redirect_to :back
  end

  def show
    @likes = current_user.likes
  end

  def edit
  end

  def update

  end

  def delete
    like = Like.find(params[:id])
    like.delete
    return redirect_to saved_recipes_path
  end
end

app/controllers/mealplan_controller.rb
class MealplanController < ApplicationController
  def index
  end

  def new
    if session[:meal]
      @meal = Meal.find(session[:meal])
    end  
    @mealplans = Mealplan.all
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
  end

  def new
  end

  def create
    meal = Meal.new
    meal.recipe_id = params[:id]
    meal.title = params[:title]
    meal.source = params[:source]
    meal.img = params[:img]
    meal.publisher = params[:publisher]
    meal.publisher_url = params[:publisher_url]
    meal.rank = params[:rank]
    meal.user = current_user
    meal.save
    session[:meal] = meal.id

    @id = params[:id]
    @recipe = JSON.parse(Net::HTTP.get(URI.parse("http://food2fork.com/api/get?key=91c70198fb6803137c6990f067c53c0d&rId=#{@id}")))
    session[:recipe] = @recipe

    return redirect_to create_items_path
  end

  def show
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/recipes_controller.rb
require 'open-uri'
require 'net/http'

class RecipesController < ApplicationController
  

  def index
    @likes = Like.all.where(user: current_user).reverse
  end

  def new
    @keyword = params[:keyword]

    reponse = JSON.parse(Net::HTTP.get(URI.parse("http://food2fork.com/api/search?key=91c70198fb6803137c6990f067c53c0d&q=#{@keyword}")))
    print response

    @saved = Meal.all.where(user: current_user).reverse

    # recipe_ids = Like.all.where(user: current_user).pluck(:recipe_id)

    @options = response["recipe"]


    # @results = response["recipes"]
    # @results.each do |recipe|
    #   if recipe_ids.include? recipe["recipe_id"]
    #     results.pop(recipe)
    #   end
    # end   




  end



  def create
  end

  def show
    @id = params[:id]
    @recipe = JSON.parse(Net::HTTP.get(URI.parse("http://food2fork.com/api/get?key=91c70198fb6803137c6990f067c53c0d&rId=#{@id}")))
    puts @recipe 

  end

  def edit
  end

  def update
  end

  def delete
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      return redirect_to index_path
    end  
  end

  def create
    user = User.find_by_email(params[:user][:email])
    if user
      if user.try(:authenticate, params[:user][:password])
        session[:user_id] = user.id
          return redirect_to index_path
      end 
    else
      flash[:errors] = ["Email and password do not match"]
      return redirect_to login_page_path
    end  
  end

  def destroy
    session.delete(:user_id) if session[:user_id]
    return redirect_to "/login"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    if current_user  
      return redirect_to index_path
    end 
  end

  def create
    user = User.new(user_params)
    if user.valid?
      user.save
      session[:user_id]= user.id
      return redirect_to index_path
    end
    flash[:errors] = user.errors.full_messages    
    return redirect_to :back
  end

  def show
    @user = current_user
    return render "/users/show.html.erb"
  end

  def edit
  end

  def update
    user = update_user(user_params)
    if user.valid?
      user.save
      return redirect_to user_path
    end  
    return redirect_to index_path
  end

  def delete
  end

  private
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
    end 

    def update_user(params)
    user = User.find(current_user.id)
    user.firstname = params[:firstname]
    user.lastname = params[:lastname]
    user.email = params[:email]
    user.save
    return user
    end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mealplan_helper.rb
module MealplanHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/delete.html.erb
<h1>Recipes#delete</h1>
<p>Find me in app/views/recipes/delete.html.erb</p>

app/views/recipes/edit.html.erb
<h1>Recipes#edit</h1>
<p>Find me in app/views/recipes/edit.html.erb</p>

app/views/recipes/index.html.erb
<h2>Welcome, <%= current_user.username%></h2>


<h3>Search for Recipes</h3>
<form class="form" action="/recipes/new" method="post">
<input type="hidden" name="authenticity_token" placeholder="<%= form_authenticity_token %>">
<input type="text" name="keyword" placeholder="Keyword to Search">
<input type="submit" value="Find">
</form>

app/views/recipes/new.html.erb
<h1>Recipes</h1>

<div class="row">

<div class="col-sm-6">	


<h3>Search for Recipes</h3>
<form class="form" action="/recipes/new" method="post">
<input type="hidden" name="authenticity_token" placeholder="<%= form_authenticity_token %>">
<input type="text" name="keyword" placeholder="Keyword to Search">
<input type="submit" value="Submit">
</form>


<% if @options %>
<% @options.each do |recipe| %>

<h3><%= link_to "#{recipe["title"]}", show_recipe_path(id: recipe["recipe_id"]), method: :post %></h3>

<%= link_to "Save", add_meal_path(
  id: @recipe['recipe_id'], 
  title: @recipe['title'], 
  source: @recipe['source_url'],
  img: @recipe['image_url'], 
  publisher: @recipe["publisher"], 
  publisher_url: @recipe["publisher_url"], 
  rank: @recipe["social_rank"], 
  ing: @recipe['ingredients']
  ), 
  method: :post %>


<p><%= link_to "#{recipe["publisher"]}", "#{recipe["publisher_url"]}" %></p>
<p>Public Ranking: <%= recipe["social_rank"] %></p>
<p><img src="<%= recipe["image_url"] %>" /></p>

<% end %>
<% end %>
</div>

<div class="col-sm-6">	

<h3>Recipes You Have Saved</h3>

<% if @saved %>
<% @saved.each do |meal| %>

<h4><%= link_to "#{meal.title}", show_meal_path(id: meal['meal_id']), method: :post %></h4>
<%= link_to "Unsave", delete_meal_path(id: meal.id), method: :delete%> 
<p><%= link_to "#{meal.publisher}", "#{meal.publisher_url}" %></p>
</div>

<% end %>
<% end %>




</div>
</div>

app/views/recipes/show.html.erb
<div class="row">
	<h2><%= @recipe['recipe']['title'].titleize %></h2>

<%= link_to "Add to Meal Plan", add_meal_path(
	id: @recipe['recipe']['recipe_id'], 
	title: @recipe['recipe']['title'], 
	source: @recipe['recipe']['source_url'], 
	img: @recipe['recipe']['image_url'], 
	publisher: @recipe['recipe']["publisher"], 
	publisher_url: @recipe['recipe']["publisher_url"], 
	rank: @recipe['recipe']["social_rank"], 
	ing: @recipe['recipe']['ingredients']
	), 
	method: :post  %>
| <%= link_to "View Directions", "#{@recipe['recipe']['source_url']}" %>
</div>	

<div class="row">

<div class="col-sm-4">

<p> <img src="<%=@recipe['recipe']['image_url']%>"> </p>

</div>
<div class="col-sm-4">
<p><%= link_to "#{@recipe['recipe']["publisher"]}", "#{@recipe['recipe']["publisher_url"]}" %></p>
<p>Public Ranking: <%= @recipe['recipe']["social_rank"] %></p>



<h3> Ingredients: </h3>

<% @recipe['recipe']['ingredients'].each do |ing| %>

<p> <%= ing %> </p>

<% end %>

</div>

</div>

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>