config/routes.rb
Rails.application.routes.draw do
  
  root 'users#new'

  get 'sessions/index'

  get 'login' => 'sessions#new', as: 'login_page'

  post 'login' => 'sessions#create', as: 'login'

  get 'sessions/show'

  get 'sessions/edit'

  get 'sessions/update'

  get 'logout' => 'sessions#destroy', as: 'logout'

  get 'users/index' => 'users#index' 

  get 'register' => 'users#new', as: 'register_page'

  post 'register' => 'users#create', as: 'register'

  get 'showuser' => 'users#show', as: 'user'

  get 'users/edit' => 'users#edit', as: 'edit_user'

  patch 'users/update' => 'users#update', as: 'update_user'

  get 'users/delete'


  #LIKES STUFF

  get 'likes/index'

  get 'likes/new'

  get 'likes/create' => 'likes#create', as: 'save_recipe'

  post 'likes/create' => 'likes#create', as: 'add_recipe'

  get 'likes/show' => 'likes#show', as: 'saved_recipes'

  get 'likes/edit'

  get 'likes/update'

  delete 'likes/delete' => 'likes#delete', as: 'unsave_recipe'

# RECIPES

  get 'recipes/index' => 'recipes#index', as: "index"

  get 'recipes/new' => 'recipes#new', as: "find_recipes"

  post 'recipes/new' => 'recipes#new', as: "search_recipes"

  get 'recipes/create' 

  post 'recipes/show' => 'recipes#show', as: 'show_recipe'

  get 'recipes/edit'

  get 'recipes/update'

  delete 'recipes/delete'

#MEALS 

  get 'meals/index'

  get 'meals/new'

  post 'meals/create' => 'meals#create', as: 'add_meal'

  post 'meals/show' => 'meals#show', as: 'show_meal'

  get 'meals/edit'

  get 'meals/update'

  delete 'meals/delete' => 'meals#delete', as: 'delete_meal'

 #MEALPLAN
 
  get 'mealplan/index' => 'mealplan#index', as: 'mealplans'

  get 'mealplan/new' => 'mealplan#new', as: 'start_mealplan'

  post 'mealplan/new' => 'mealplan#new', as: 'new_mealplan'

  post 'mealplan/create' => 'mealplan#create', as: 'create_mealplan'

  get 'mealplan/show' 

  get 'mealplan/edit'

  get 'mealplan/update'

  delete 'mealplan/delete' 

#ITEMS

  get 'items/index'

  get 'items/new'

  get 'items/create' => 'items#create', as: 'create_items'

  get 'items/show' 

  get 'items/edit'

  get 'items/update'

  delete 'items/delete'

  #INGREDIENTS

  get 'ingredients/index'

  get 'ingredients/new'

  get 'ingredients/create' => 'ingredients#create', as: "add_ingredient"

  get 'ingredients/show' 

  get 'ingredients/edit'

  get 'ingredients/update'

  delete 'ingredients/delete'

end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
  end

  def new
  end

  def create
    like = Like.new
    like.title = params[:title]
    like.recipe_id = params[:id]
    like.publisher = params[:publisher]
    like.publisher_url = params[:publisher_url]
    like.rank = params[:rank]
    like.img = params[:img]
    like.user = current_user
    like.save
    return redirect_to :back
  end

  def show
    @likes = current_user.likes
  end

  def edit
  end

  def update

  end

  def delete
    like = Like.find(params[:id])
    like.delete
    return redirect_to saved_recipes_path
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/delete.html.erb
<h1>Likes#delete</h1>
<p>Find me in app/views/likes/delete.html.erb</p>

app/views/likes/edit.html.erb
<h1>Likes#edit</h1>
<p>Find me in app/views/likes/edit.html.erb</p>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/likes/show.html.erb
<div class="row">
<div class="col-sm-12">	

<h3>Recipes You Have Saved</h3>

<% if @likes %>
<% @likes.each do |recipe| %>

<h3><%= link_to "#{recipe.title}", show_recipe_path(id: recipe['recipe_id']), method: :post %></h3>
<%= link_to "Unsave", unsave_recipe_path(id: recipe.id), method: :delete%> 
<p><%= link_to "#{recipe.publisher}", "#{recipe.publisher_url}" %></p>
<p>Public Ranking: <%= recipe.rank %></p>
<p><img src="<%= recipe.img %>" /></p>
</div>

<% end %>
<% end %>




</div>
</div>

app/views/likes/update.html.erb
<h1>Likes#update</h1>
<p>Find me in app/views/likes/update.html.erb</p>